Enhavo\Bundle\MediaBundle\Entity\File:
    type: entity
    table: media_file
    repositoryClass: Enhavo\Bundle\MediaBundle\Repository\FileRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mimeType:
            type: string
            length: 255
            nullable: true

        extension:
            type: string
            length: 255
            nullable: true

        order:
            type: integer
            column: '`order`'
            nullable: true

        filename:
            type: string
            length: 255
            nullable: true

        parameters:
              type: array
              nullable: true

        token:
            type: string
            nullable: true

        md5Checksum:
            type: string
            nullable: true

        library:
            type: boolean
            nullable: true

        garbage:
            type: boolean
            nullable: false

        garbageTimestamp:
            type: datetime
            nullable: true

        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create

    lifecycleCallbacks: {  }
