esperanto\MediaBundle\Entity\File:
    type: entity
    table: media_file
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mimeType:
            type: string
            length: 255
            nullable: true

        extension:
            type: string
            length: 255
            nullable: true

        order:
            type: integer
            column: '`order`'
            nullable: true

        filename:
            type: string
            length: 255
            nullable: true

        title:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
