enhavo_media_theme_file:
    path:  /media/file/{id}/{shortChecksum}/{filename}.{extension}
    methods: [GET]
    defaults:
        _expose: [theme]
        _endpoint:
            type: media_file
            repository_arguments:
                - id: expr:request.get("id")
                  filename: expr:request.get("filename")
                  extension: expr:request.get("extension")
                  shortChecksum: expr:request.get("shortChecksum")
