enhavo_media_theme_format:
    path:  /media/format/{id}/{format}/{shortMd5Checksum}/{filename}
    methods: [GET]
    defaults:
        _expose: [theme, admin]
        _endpoint:
            type: media_format
            find_by: [id, filename]
            checksum_test: true
            checksum_parameter: shortMd5Checksum
