enhavo_media_upload:
    path:  /file/add
    defaults:
        _controller: enhavo_media.controller.upload:uploadAction

enhavo_media_replace:
    path:  /file/replace/{token}
    methods: [POST]
    defaults:
        _controller: enhavo_media.controller.upload:replaceAction
    options:
        expose: true

enhavo_media_resolve:
    path:  /file/resolve/{token}
    methods: [POST]
    defaults:
        _controller: enhavo_media.controller.file:resolveAction
    options:
        expose: true

enhavo_media_download:
    path:  /file/download/{id}/{md5ShortChecksum}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:downloadAction
        _method: GET
        filename: ~

enhavo_media_show:
    path:  /file/show/{id}/{md5ShortChecksum}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:showAction
        width: ~
        height: ~
        filename: ~
        _method: GET
    options:
        expose: true

enhavo_media_format:
    path:  /file/format/{id}/{format}/{md5ShortChecksum}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:showFormatAction
        _method: GET
    options:
        expose: true

