enhavo_media_upload:
    path:  /file/add
    defaults:
        _controller: enhavo_media.controller.file:uploadAction

enhavo_media_replace:
    path:  /file/replace/{id}
    methods: [POST]
    defaults:
        _controller: enhavo_media.controller.file:replaceAction
    options:
        expose: true

enhavo_media_download:
    path:  /file/download/{id}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:downloadAction
        _method: GET
        filename: ~

enhavo_media_show_two_dim:
    path:  /file/{id}/{width}/{height}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:showAction
        _method: GET
        filename: ~
    requirements:
        width: \d+
        height: \d+

enhavo_media_show_one_dim:
    path:  /file/{id}/{width}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:showAction
        height: ~
        _method: GET
        filename: ~
    requirements:
        width: \d+

enhavo_media_show:
    path:  /file/{id}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:showAction
        width: ~
        height: ~
        filename: ~
        _method: GET
    options:
        expose: true
