enhavo_media_upload:
    path:  /file/add
    defaults:
        _controller: enhavo_media.controller.upload:uploadAction

enhavo_media_replace:
    path:  /file/replace/{token}
    methods: [POST]
    defaults:
        _controller: enhavo_media.controller.upload:replaceAction
    options:
        expose: true

enhavo_media_resolve:
    path:  /file/resolve/{token}
    methods: [GET]
    defaults:
        _controller: enhavo_media.controller.file:resolveAction
    options:
        expose: true

enhavo_media_resolve_format:
    path:  /file/resolve/{token}/{format}
    methods: [GET]
    defaults:
        _controller: enhavo_media.controller.file:resolveFormatAction
    options:
        expose: true

enhavo_media_download:
    path:  /file/download/{id}/{shortMd5Checksum}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:downloadAction
        _method: GET
        filename: ~

enhavo_media_show:
    path:  /file/show/{id}/{shortMd5Checksum}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:showAction
        width: ~
        height: ~
        filename: ~
        _method: GET
    options:
        expose: true

enhavo_media_format:
    path:  /file/format/{id}/{format}/{shortMd5Checksum}/{filename}
    defaults:
        _controller: enhavo_media.controller.file:showFormatAction
        _method: GET
    options:
        expose: true

enhavo_media_compatible_show:
    path: /file/compatible/show/{id}
    defaults:
        _controller: enhavo_media.controller.file:showCompatibleAction
        _method: GET
    options:
        expose: true

enhavo_media_compatible_format:
    path: /file/compatible/show/{id}/{format}
    defaults:
        _controller: enhavo_media.controller.file:showCompatibleAction
        _method: GET
    options:
        expose: true

enhavo_media_compatible_download:
    path: /file/compatible/download/{id}
    defaults:
        _controller: enhavo_media.controller.file:downloadCompatibleAction
        _method: GET
    options:
        expose: true

enhavo_media_compatible_replace:
    path: /file/compatible/replace/{id}
    defaults:
        _controller: enhavo_media.controller.upload:replaceCompatibleAction
        _method: GET
    options:
        expose: true


enhavo_media_image_cropper_crop:
    path:  /media/image/cropper
    methods: [POST]
    defaults:
        _controller: EnhavoMediaBundle:ImageCropper:crop
    options:
        expose: true