enhavo_media_upload:
    pattern:  /file/add
    defaults:
        _controller: EnhavoMediaBundle:File:upload

enhavo_media_show_two_dim:
    pattern:  /file/{id}/{width}/{height}/{slug}
    defaults: { _controller: EnhavoMediaBundle:File:show,slug:'',_method: GET}
    requirements: {width: \d+,height: \d+}

enhavo_media_show_one_dim:
    pattern:  /file/{id}/{width}/{slug}
    defaults: { _controller: EnhavoMediaBundle:File:show,height:'',slug:'',_method: GET}
    requirements: {width: \d+}

enhavo_media_show:
    pattern:  /file/{id}/{slug}
    defaults: { _controller: EnhavoMediaBundle:File:show,width:'',height:'',slug:'',_method: GET}