Enhavo\Bundle\MediaBundle\Entity\File:
    attributes:
        id:
            groups: ['media']
        checksum:
            groups: ['media']
        filename:
            groups: ['media']
        mimeType:
            groups: ['media']
        extension:
            groups: ['media']
        token:
            groups: ['media', 'media_private']