parameters:
    esperanto_media.form.files_type.class: esperanto\MediaBundle\Form\Type\FilesType
    esperanto_media.upload.class: esperanto\MediaBundle\Service\UploadService
    esperanto_media.twig_extension.class: esperanto\MediaBundle\Twig\MediaExtension

services:
    esperanto_media_files:
        class: %esperanto_media.form.files_type.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: esperanto_files }

    esperanto_media.upload:
        class: %esperanto_media.upload.class%
        arguments:
            - %kernel.root_dir%/media
            - @doctrine.orm.entity_manager


    esperanto_media.twig_extension:
        class: %esperanto_media.twig_extension.class%
        arguments:
            - @service_container
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }