parameters:
    enhavo_media.form.files_type.class: Enhavo\Bundle\MediaBundle\Form\Type\FilesType
    enhavo_media.upload.class: Enhavo\Bundle\MediaBundle\Service\UploadService
    enhavo_media.twig_extension.class: Enhavo\Bundle\MediaBundle\Twig\MediaExtension

services:
    enhavo_media_files:
        class: %enhavo_media.form.files_type.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: enhavo_files }

    enhavo_media.upload:
        class: %enhavo_media.upload.class%
        arguments:
            - %kernel.root_dir%/media
            - @doctrine.orm.entity_manager


    enhavo_media.twig_extension:
        class: %enhavo_media.twig_extension.class%
        arguments:
            - @service_container
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }