parameters:
    enhavo_media.form.files_type.class: Enhavo\Bundle\MediaBundle\Form\Type\FilesType
    enhavo_media.file_service.class: Enhavo\Bundle\MediaBundle\Service\FileService
    enhavo_media.twig_extension.class: Enhavo\Bundle\MediaBundle\Twig\MediaExtension
    enhavo_media.lifecycle_listener.class: Enhavo\Bundle\MediaBundle\EventListener\LifecycleListener
    enhavo_media.controller.file_controller.class: Enhavo\Bundle\MediaBundle\Controller\FileController

services:
    enhavo_media_files:
        class: '%enhavo_media.form.files_type.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: enhavo_files }

    enhavo_media.file_service:
        class: '%enhavo_media.file_service.class%'
        arguments:
            - '%kernel.root_dir%/media'
            - '@doctrine.orm.entity_manager'
            - '@enhavo_media.format_manager'

    enhavo_media.format_manager:
        class: Enhavo\Bundle\MediaBundle\Media\FormatManager
        arguments:
            - '%kernel.root_dir%/media'
            - '@filesystem'
            - '%enhavo_media.formats%'

    enhavo_media.twig_extension:
        class: '%enhavo_media.twig_extension.class%'
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }

    enhavo_media.lifecycle_listener:
        class: '%enhavo_media.lifecycle_listener.class%'
        arguments:
             - '@service_container'
        tags:
            - { name: doctrine.event_listener, event: preRemove }
            - { name: kernel.event_listener, event: enhavo_app.create, method: collectGarbage }
            - { name: kernel.event_listener, event: enhavo_app.update, method: collectGarbage }

    enhavo_media.table.picture_widget:
        class: Enhavo\Bundle\MediaBundle\Table\Widget\PictureWidget
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: enhavo.table_widget, alias: picture }

    enhavo_media.factory.file:
        class: Enhavo\Bundle\MediaBundle\Factory\FileFactory
        arguments:
            - 'Enhavo\Bundle\MediaBundle\Entity\File'
            - '%kernel.root_dir%/media'
            - '@doctrine.orm.entity_manager'

    enhavo_media.controller.file:
        class: '%enhavo_media.controller.file_controller.class%'
        arguments:
            - '@enhavo_media.file_service'
        calls:
            - [setContainer, ['@service_container']]