services:
    Enhavo\Bundle\MediaBundle\FileNotFound\ExceptionFileNotFoundHandler:

    Enhavo\Bundle\MediaBundle\FileNotFound\RemoteFileNotFoundHandler:
        arguments:
            - '@Enhavo\Bundle\MediaBundle\Routing\UrlGeneratorInterface'
            - '@http_client'

    Enhavo\Bundle\MediaBundle\FileNotFound\CreateDummyFileNotFoundHandler:
        arguments:
            - '@filesystem'
            - '%kernel.project_dir%/var/media/dummy'
