enhavo_media_image_cropper_crop:
    path:  /media/image/{token}/{format}/cropper/crop
    methods: [POST]
    defaults:
        _controller: enhavo_media.controller.image_cropper:cropAction
    options:
        expose: true

enhavo_media_image_cropper_data:
    path:  /media/image/{token}/{format}/cropper/data
    methods: [GET]
    defaults:
        _controller: enhavo_media.controller.image_cropper:dataAction
    options:
        expose: true