enhavo_media_library_index:
    path:  /media/library/index
    methods: [GET]
    options:
        expose: true
    defaults:
        _controller: enhavo_media.controller.library:indexAction
        _sylius:
            viewer:
                blocks:
                    media_library:
                        type: media_library

enhavo_media_library_upload:
    path:  /media/library/upload
    methods: [POST]
    options:
        expose: true
    defaults:
        _controller: enhavo_media.controller.library:uploadAction

enhavo_media_library_list:
    path:  /media/library/list
    methods: [POST, GET]
    options:
        expose: true
    defaults:
        _controller: enhavo_media.controller.file:tableAction
        _sylius:
            permission: ROLE_ENHAVO_MEDIA_LIBRARY_INDEX
            criteria:
                library: true
            sorting:
                createdAt: desc
            paginate: 30
            template: 'EnhavoMediaBundle:Block:list.html.twig'
            viewer:

enhavo_media_library_update:
    options:
        expose: true
    path: /media/library/update/{id}
    methods: [GET,POST]
    defaults:
        _controller: enhavo_media.controller.file:updateAction
        _sylius:
            form: enhavo_media_library_file
            permission: ROLE_ENHAVO_MEDIA_LIBRARY_UPDATE
            viewer:
                form:
                    action: enhavo_media_library_update
                    delete: enhavo_media_library_delete
                tabs:
                    file:
                        label: file.label.file
                        template: 'EnhavoMediaBundle:Admin/Library:file.html.twig'

enhavo_media_library_delete:
    options:
        expose: true
    path: /media/library/delete/{id}
    methods: [DELETE]
    defaults:
        _controller: enhavo_media.controller.file:deleteAction
        _sylius:
            redirect:
                route: enhavo_media_library_list

