enhavo_media_admin_image_cropper:
    path: /image-cropper/{token}/{format}
    defaults:
        _expose: admin
        _vue:
            component: media-image-cropper
            groups: admin
        _endpoint:
            type: admin
