twig:
    form:
        resources:
            - 'EnhavoMediaBundle:Form:media.html.twig'
            - 'EnhavoMediaBundle:Form:image-cropper.html.twig'

doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\MediaBundle\Model\FileInterface: Enhavo\Bundle\MediaBundle\Entity\File

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        news_thumb:
            quality: 75
            filters:
                thumbnail: { size: [300, 110], mode: outbound }

enhavo_app:
    stylesheets:
        - '@EnhavoMediaBundle/Resources/public/css/style.css'
    apps:
        - 'media/Adapter/EnhavoAdapter'
        - 'media/Extension/ImageCropper'
        - 'media/Extension/MediaLibrary'

enhavo_assets:
    require_js:
        paths:
            media:
                location: /bundles/enhavomedia/js/media

enhavo_media:
    formats:
        enhavoTableThumb:
            type: image
            width: 60
            height: 60
        enhavoPreviewThumb:
            type: image
            width: 72
            height: 72