doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\MediaBundle\Model\FileInterface: Enhavo\Bundle\MediaBundle\Entity\File
            Enhavo\Bundle\MediaBundle\Model\FormatInterface: Enhavo\Bundle\MediaBundle\Entity\Format

enhavo_app:
    template_paths:
        enhavo_media:
            path: '@EnhavoMediaBundle/Resources/views'
            alias: EnhavoMedia
            priority: 10

enhavo_media:
    formats:
        enhavoTableThumb:
            type: image
            width: 60
            height: 60
        enhavoPreviewThumb:
            type: image
            width: 72
            height: 72
    form:
        default:
            route: enhavo_media_admin_api_file_upload
            actions_file:
                download:
                    type: media_download
                format:
                    type: media_format
