twig:
    form_themes:
        - 'EnhavoMediaBundle:Form:media.html.twig'
        - 'EnhavoMediaBundle:Form:image-cropper.html.twig'

doctrine:
    orm:
        resolve_target_entities:
            Enhavo\Bundle\MediaBundle\Model\FileInterface: Enhavo\Bundle\MediaBundle\Entity\File

enhavo_app:
#    stylesheets:
#        - '@EnhavoMediaBundle/Resources/public/css/style.css'
    apps:
        - 'media/Adapter/EnhavoAdapter'
        - 'media/Extension/ImageCropper'
        - 'media/Extension/MediaLibrary'
    roles:
        enhavo_media_library_index:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_INDEX
            label: library.role.label.index
            translationDomain: EnhavoMediaBundle
        enhavo_media_library_create:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_CREATE
            label: library.role.label.create
            translationDomain: EnhavoMediaBundle
        enhavo_media_library_update:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_UPDATE
            label: library.role.label.update
            translationDomain: EnhavoMediaBundle
        enhavo_media_library_delete:
            role: ROLE_ENHAVO_MEDIA_LIBRARY_DELETE
            label: library.role.label.delete
            translationDomain: EnhavoMediaBundle


enhavo_media:
    formats:
        enhavoTableThumb:
            type: image
            width: 60
            height: 60
        enhavoPreviewThumb:
            type: image
            width: 72
            height: 72
        enhavoMediaLibraryThumb:
            type: image
            width: 150
            height: 150
        enhavoMediaLibrary:
            type: image
            maxWidth: 640
            maxHeight: 480