enhavo_media_admin_api_file:
    path:  /file/{token}
    methods: [GET]
    defaults:
        _expose: admin_api
        _endpoint:
            type: media_file

enhavo_media_admin_api_file_replace:
    path:  /file/replace/{token}
    methods: [GET]
    defaults:
        _expose: admin_api
        _endpoint:
            type: media_file_replace

enhavo_media_admin_api_file_upload:
    path:  /file/upload
    methods: [POST]
    defaults:
        _expose: admin_api
        _endpoint:
            type: media_file_upload
